### ISSUE TITLE
ARM jit integration

### ISSUE THREAD

**Issue by bentokun** [bentokun/EKA2L1#4]

**Comment by huckleberrypie** [comment]
Have you tried the likes of Exophase on IRC? That or those who are developing Nintendo DS emulators or similar? There might be some generic or reference ARM emulation cores which you may be able to use as a starting point.

**Comment by bentokun** [comment]
No, I haven't tried yet. I'm not used to chatting on IRC.
About the ARM core, I have seen and adapted the JIT from some project like
Citra, Yuzu and Vita3K (which happens to use ARM11 or other), and I'm
working with the JIT along with the memory.

If needed, I will reach out to Exophase guys to ask. Thanks for the
interest in this project :)

2018-04-09 16:54 GMT+07:00 Huck Jones <notifications@github.com>:

**Comment by huckleberrypie** [comment]
Yeah, that might be of some help. I am by no means a pro coder, but I am nonetheless interested in emulation.

**Comment by bentokun** [comment]
Done using Unicorn.
